import { books as full } from '../booksets/full-books';
import { books as ob } from '../booksets/other-books';
import type { IndexBookset } from '../../internal/books/book-type';

export const index_books: IndexBookset = {
	Moses_ord: new Set([...full.Moses_ord, ...ob.Moses_ord]),
	Genesis: new Set([...full.Genesis, ...ob.Genesis]),
	Exodus: new Set([...full.Exodus, ...ob.Exodus]),
	Leviticus: new Set([...full.Leviticus, ...ob.Leviticus]),
	Numbers: new Set([...full.Numbers, ...ob.Numbers]),
	Deuteronomy: new Set([...full.Deuteronomy, ...ob.Deuteronomy]),
	Josua: new Set([...full.Josua, ...ob.Josua]),
	Judges: new Set([...full.Judges, ...ob.Judges]),
	Ruth: new Set([...full.Ruth, ...ob.Ruth]),
	Samuel: new Set([...full.Samuel, ...ob.Samuel]),
	Kings: new Set([...full.Kings, ...ob.Kings]),
	Chronicles: new Set([...full.Chronicles, ...ob.Chronicles]),
	Ezra: new Set([...full.Ezra, ...ob.Ezra]),
	Nehemia: new Set([...full.Nehemia, ...ob.Nehemia]),
	Esther: new Set([...full.Esther, ...ob.Esther]),
	Job: new Set([...full.Job, ...ob.Job]),
	Psalms: new Set([...full.Psalms, ...ob.Psalms]),
	Proverbs: new Set([...full.Proverbs, ...ob.Proverbs]),
	Ecclesiastes: new Set([...full.Ecclesiastes, ...ob.Ecclesiastes]),
	// Song_of_Solomon -> Song of Solomon | Canticle of Canticles
	Songs_Of_Solomon: new Set([...full.Songs_Of_Solomon, ...ob.Songs_Of_Solomon]), // Through abbreviations
	Isaiah: new Set([...full.Isaiah, ...ob.Isaiah]),
	Jeremiah: new Set([...full.Jeremiah, ...ob.Jeremiah]),
	Lamentations: new Set([...full.Lamentations, ...ob.Lamentations]),
	Ezekiel: new Set([...ob.Ezekiel, ...ob.Ezekiel]),
	Daniel: new Set([...ob.Daniel, ...full.Daniel]),
	Hosea: new Set([...ob.Hosea, ...full.Hosea]),
	Joel: new Set([...ob.Joel, ...full.Joel]),
	Amos: new Set([...ob.Amos, ...full.Amos]),
	Obadiah: new Set([...ob.Obadiah, ...full.Obadiah]),
	Jonah: new Set([...ob.Jonah, ...full.Jonah]),
	Micah: new Set([...ob.Micah, ...full.Micah]),
	Nahum: new Set([...ob.Nahum, ...full.Nahum]),
	Habakkuk: new Set([...ob.Habakkuk, ...full.Habakkuk]),
	Zephaniah: new Set([...ob.Zephaniah, ...full.Zephaniah]),
	Haggai: new Set([...ob.Haggai, ...full.Haggai]),
	Zechariah: new Set([...ob.Zechariah, ...full.Zechariah]),
	Malachi: new Set([...ob.Malachi, ...full.Malachi]),
	Matthew: new Set([...ob.Matthew, ...full.Matthew]),
	Mark: new Set([...ob.Mark, ...full.Mark]),
	Luke: new Set([...ob.Luke, ...full.Luke]),
	John: new Set([...ob.John, ...full.John]),
	Acts: new Set([...ob.Acts, ...full.Acts]),
	Romans: new Set([...ob.Romans, ...full.Romans]),
	Corinthians: new Set([...ob.Corinthians, ...full.Corinthians]),
	Galatians: new Set([...ob.Galatians, ...full.Galatians]),
	Ephesians: new Set([...ob.Ephesians, ...full.Ephesians]),
	Philippians: new Set([...ob.Philippians, ...full.Philippians]),
	Colossians: new Set([...ob.Colossians, ...full.Colossians]),
	Thessalonians: new Set([...ob.Thessalonians, ...full.Thessalonians]),
	Timothy: new Set([...ob.Timothy, ...full.Timothy]),
	Titus: new Set([...ob.Titus, ...full.Titus]),
	Philemon: new Set([...ob.Philemon, ...full.Philemon]),
	Hebrews: new Set([...ob.Hebrews, ...full.Hebrews]),
	James: new Set([...ob.James, ...full.James]),
	Peter: new Set([...ob.Peter, ...full.Peter]),
	John_epistles: new Set([...ob.John_epistles, ...full.John_epistles]),
	Jude: new Set([...ob.Jude, ...full.Jude]),
	Revelation: new Set([...ob.Revelation, ...full.Revelation]),
	Tobit: new Set([...ob.Tobit, ...full.Tobit]),
	Judith: new Set([...ob.Judith, ...full.Judith]),
	Esther_Greek: new Set([...ob.Esther_Greek, ...full.Esther_Greek]),
	Wisdom_Of_Solomon: new Set([...ob.Wisdom_Of_Solomon, ...full.Wisdom_Of_Solomon]),
	Sirach: new Set([...ob.Sirach, ...full.Sirach]),
	Baruch: new Set([...ob.Baruch, ...full.Baruch]),
	Letter_Of_Jeremiah: new Set([...ob.Letter_Of_Jeremiah, ...full.Letter_Of_Jeremiah]),
	Song_Of_The_Three_Young_Men: new Set([
		...full.Song_Of_The_Three_Young_Men,
		...ob.Song_Of_The_Three_Young_Men,
	]), // TODO: Song of the three young men | Other
	Susanna: new Set([...ob.Susanna, ...full.Susanna]),
	Bel_And_The_Dragon: new Set([...ob.Bel_And_The_Dragon, ...full.Bel_And_The_Dragon]),
	Maccabees: new Set([...ob.Maccabees, ...full.Maccabees]),
	Esdras: new Set([...ob.Esdras, ...full.Esdras]),
	Prayer_Of_Manasseh: new Set([...ob.Prayer_Of_Manasseh, ...full.Prayer_Of_Manasseh]),
	Psalm_151: new Set([...ob.Psalm_151, ...full.Psalm_151]),
	Letter_To_The_Laodiceans: new Set([
		...ob.Letter_To_The_Laodiceans,
		...ob.Letter_To_The_Laodiceans,
	]),
	Prayer_Of_Azariah: new Set([...ob.Prayer_Of_Azariah, ...full.Prayer_Of_Azariah]),
	Psalms_152_To_155: new Set([...ob.Psalms_152_To_155, ...full.Psalms_152_To_155]),
	Odes: new Set([...ob.Odes, ...full.Odes]),
	Psalms_Of_Solomon: new Set([...ob.Psalms_Of_Solomon, ...full.Psalms_Of_Solomon]),
	Letter_Of_Baruch: new Set([...ob.Letter_Of_Baruch, ...full.Letter_Of_Baruch]),
	Jubilees: new Set([...ob.Jubilees, ...full.Jubilees]),
	Enoch: new Set([...ob.Enoch, ...full.Enoch]),
	Reproof: new Set([...ob.Reproof, ...full.Reproof]), // Proverbs part 2: Used in the Ethiopian Bible
	Baruch_epistles: new Set([...ob.Baruch_epistles, ...full.Baruch_epistles]),
	Meqabyan: new Set([...ob.Meqabyan, ...full.Meqabyan]),
};
