import type { LanguageOptions } from '../internal/lang-type';

export const language: LanguageOptions = {
	allowed_beginning_idents: ['beg', 'start', 'beginning'],
	allowed_ending_idents: ['end', 'ending'],
	allowed_book_delimiters: [';'],
	allowed_chapter_delimiters: [';'],
	allowed_verse_seperators: [','],
	allowed_chapter_verse_seperators: [':'],
	allowed_range_characters: ['-'],
	allowed_number_sets: new Set<string>(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']),
	allowed_character_sets: new Set<string>([
		'a',
		'b',
		'c',
		'd',
		'e',
		'f',
		'g',
		'h',
		'i',
		'j',
		'k',
		'l',
		'm',
		'n',
		'o',
		'p',
		'q',
		'r',
		's',
		't',
		'u',
		'v',
		'w',
		'x',
		'y',
		'z',
	]),
};
