import type { Bookset } from '../../internal/books/book-type';

export const books: Bookset = {
	//
	// Old Testament
	Moses_ord: [],
	Genesis: ['Gen.'],
	Exodus: ['Exod.'],
	Leviticus: ['Lev.'],
	Numbers: ['Num.'],
	Deuteronomy: ['Deut.'],
	Josua: ['Josh.'],
	Judges: ['Judg.'],
	Ruth: ['Ruth'],
	Samuel: ['Sam.'],
	Kings: ['Kings'],
	Chronicles: ['Chron.'],
	Ezra: ['Ezra'],
	Nehemia: ['Neh.'],
	Esther: ['Esth.'],
	Job: ['Job'],
	Psalms: ['Ps.'],
	Proverbs: ['Prov.'],
	Ecclesiastes: ['Eccles.', 'Qoh.'],
	// Song_of_Solomon -> Song of Solomon | Canticle of Canticles
	Songs_Of_Solomon: [],
	Isaiah: ['Isa.'],
	Jeremiah: ['Jer.'],
	Lamentations: ['Lam.'],
	Ezekiel: ['Ezek.'],
	Daniel: ['Dan.'],
	Hosea: ['Hos.'],
	Joel: ['Joel'],
	Amos: ['Amos'],
	Obadiah: ['Obad.'],
	Jonah: ['Jon.'],
	Micah: ['Mic.'],
	Nahum: ['Nah.'],
	Habakkuk: ['Hab.'],
	Zephaniah: ['Zeph.'],
	Haggai: ['Hag.'],
	Zechariah: ['Zech.'],
	Malachi: ['Mal.'],

	//
	// New Testament
	Matthew: ['Matt.'],
	Mark: ['Mark'],
	Luke: ['Luke'],
	John: ['John'],
	Acts: ['Act', 'Ac'],
	Romans: ['Rom.'],
	Corinthians: ['Cor.'],
	Galatians: ['Gal.'],
	Ephesians: ['Eph.'],
	Philippians: ['Phil.'],
	Colossians: ['Col.'],
	Thessalonians: ['Thess.'],
	Timothy: ['Tim.'],
	Titus: ['Tit.'],
	Philemon: ['Philem.'],
	Hebrews: ['Heb.'],
	James: ['Jas.'],
	Peter: ['Pet.'],
	John_epistles: ['John'],
	Jude: ['Jude'],
	Revelation: ['Apoc.', 'Rev.'],

	//
	// Apocrypha
	Tobit: ['Tob.'],
	Judith: ['Jth.'],
	Esther_Greek: ['Esth.'], // MLA means Esther (Apocrypha)
	Wisdom_Of_Solomon: ['Wisd.'],

	Sirach: ['Sir.', 'Ecclus.'],
	Baruch: ['Bar.'],

	Letter_Of_Jeremiah: [],
	Song_Of_The_Three_Young_Men: [],
	Susanna: ['Sus.'],
	Bel_And_The_Dragon: [],
	Maccabees: ['Macc.'],
	Esdras: ['Esd.'],
	Prayer_Of_Manasseh: [],
	Psalm_151: [],
	Letter_To_The_Laodiceans: [],
	Prayer_Of_Azariah: [],
	Psalms_152_To_155: [],
	Psalms_Of_Solomon: [],
	Odes: [],
	Letter_Of_Baruch: [],
	Reproof: [],
	Baruch_epistles: [],
	Enoch: [],
	Jubilees: [],
	Meqabyan: [],
};
