import type { Bookset } from '../../internal/books/book-type';

export const books: Bookset = {
	//
	// Old Testament
	Moses_ord: ['Moses'],
	Genesis: ['Gen.', 'Ge.', 'Gn.'],
	Exodus: ['Ex.', 'Exod.', 'Exo.'],
	Leviticus: ['Lev.', 'Le.', 'Lv.'],
	Numbers: ['Num.', 'Nu.', 'Nm.', 'Nb.'],
	Deuteronomy: ['Deut.', 'De.', 'Dt.'],
	Josua: ['Josh.', 'Jos.', 'Jsh.'],
	Judges: ['Judg.', 'Jdg.', 'Jg.', 'Jdgs.'],
	Ruth: ['Rth.', 'Ru.'],
	Samuel: ['Sam.', 'Sm.', 'S.'],
	Kings: ['Kgs.', 'Ki.', 'Kin.'],
	Chronicles: ['Chron.', 'Chr.', 'Ch.'],
	Ezra: ['Ezra', 'Ezr.', 'Ez.'],
	Nehemia: ['Neh.', 'Ne.'],
	Esther: ['Est.', 'Esth.', 'Es.'],
	Job: ['Jb.'],
	Psalms: ['Ps.', 'Pslm.', 'Psa.', 'Psm.', 'Pss.'],
	Proverbs: ['Prov', 'Pro.', 'Prv.', 'Pr.'],
	Ecclesiastes: ['Eccles.', 'Eccle.', 'Ecc.', 'Ec.', 'Qoh.'],
	// Song_of_Solomon -> Song of Solomon | Canticle of Canticles
	Songs_Of_Solomon: ['Song', 'SOS.', 'So.', 'Canticles', 'Cant.'],
	Isaiah: ['Isa.', 'Is.'],
	Jeremiah: ['Jer.', 'Je.', 'Jr.'],
	Lamentations: ['Lam.', 'La.'],
	Ezekiel: ['Ezek.', 'Eze.', 'Ezk.'],
	Daniel: ['Dan.', 'Da.', 'Dn.'],
	Hosea: ['Hos.', 'Ho.'],
	Joel: ['Jl.'],
	Amos: ['Am.'],
	Obadiah: ['Obad.', 'Ob.'],
	Jonah: ['Jnh.', 'Jon.'],
	Micah: ['Mic.', 'Mc.'],
	Nahum: ['Nah.', 'Na.'],
	Habakkuk: ['Hab.', 'Hb.'],
	Zephaniah: ['Zeph.', 'Zep.', 'Zp.'],
	Haggai: ['Hag.', 'Hg.'],
	Zechariah: ['Zech.', 'Zec.', 'Zc.'],
	Malachi: ['Mal.', 'Ml.'],

	//
	// New Testament
	Matthew: ['Matt.', 'Mt.'],
	Mark: ['Mrk', 'Mar', 'Mk', 'Mr'],
	Luke: ['Luk', 'Lk'],
	John: ['Joh', 'Jhn', 'Jn'],
	Acts: ['Act', 'Ac'],
	Romans: ['Rom.', 'Ro.', 'Rm.'],
	Corinthians: ['Cor.', 'Co.'],
	Galatians: ['Gal.', 'Ga.'],
	Ephesians: ['Eph.', 'Ephes.'],
	Philippians: ['Phil.', 'Php.', 'Pp.'],
	Colossians: ['Col.', 'Co.'],
	Thessalonians: ['Thess.', 'Thes.', 'Th.'],
	Timothy: ['Tim.', 'Ti.'],
	Titus: ['Tit', 'Ti'],
	Philemon: ['Philem.', 'Phm.', 'Pm.'],
	Hebrews: ['Heb.'],
	James: ['Jas', 'Jm'],
	Peter: ['Pet.', 'Pe.', 'Pt.', 'P.'],
	John_epistles: ['Jhn.', 'Jn.', 'J.'],
	Jude: ['Jud', 'Jd.'],
	Revelation: ['Rev', 'Re'],

	//
	// Apocrypha
	Tobit: ['Tob.', 'Tb.'],
	Judith: ['Jth.', 'Jdth.', 'Jdt.'],
	Esther_Greek: [''],
	Wisdom_Of_Solomon: ['Wisdom', 'Wis.', 'Ws.'],

	Sirach: ['Sir.', 'Ecclus.'],
	Baruch: ['Bar.'],

	Letter_Of_Jeremiah: ['LJe.'],
	Song_Of_The_Three_Young_Men: [],
	Susanna: ['Susanna'],
	Bel_And_The_Dragon: [],
	Maccabees: ['Maccabees'],
	Esdras: [],
	Prayer_Of_Manasseh: [],
	Psalm_151: [],
	Letter_To_The_Laodiceans: [],
	Prayer_Of_Azariah: [],
	Psalms_152_To_155: [],
	Psalms_Of_Solomon: [],
	Odes: [],
	Letter_Of_Baruch: [],
	Reproof: [],
	Baruch_epistles: [],
	Enoch: [],
	Jubilees: [],
	Meqabyan: [],
};
